"""Assemble the System A report (spec section 6: the six required sections).

Reads results/system_a/**/ plus index metadata and writes
results/system_a/report_system_a.md. Missing pieces are printed as MISSING
rather than silently omitted, so evaluation gaps stay visible.

    python -m systems.system_a.report
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

import shared  # noqa: F401
from shared import state
from shared.config import load_config
from shared.paths import paths

SYSTEM = "system_a"


def _latest(leg_dir: Path) -> Path | None:
    runs = sorted(p for p in leg_dir.glob("*") if p.is_dir())
    return runs[-1] if runs else None


def _load(run_dir: Path | None, pattern: str) -> Dict[str, Any] | None:
    if not run_dir:
        return None
    hits = sorted(run_dir.glob(pattern))
    return json.loads(hits[-1].read_text(encoding="utf-8")) if hits else None


def _table(headers: List[str], rows: List[List[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


def build_report() -> Path:
    cfg = load_config("system_a")
    res = paths.results_dir(SYSTEM)
    res.mkdir(parents=True, exist_ok=True)
    pins = state.load_pins()

    idx_path = res / "index_summary.json"
    indexes = json.loads(idx_path.read_text(encoding="utf-8")) if idx_path.exists() else []

    L: List[str] = ["# System A (Vanilla RAG) - Results Report\n",
                    "Generated by `python -m systems.system_a.report`.\n"]

    # 1. Setup summary
    L.append("## 1. Setup summary\n")
    emb, gen = cfg.get_path("models.embedding"), cfg.get_path("models.generation")
    L.append(_table(["Component", "Value"], [
        ["Chunking", f"RecursiveCharacterTextSplitter, size="
                     f"{cfg.get_path('chunking.chunk_size')} chars, overlap="
                     f"{cfg.get_path('chunking.chunk_overlap')} chars"],
        ["Embedding model", f"{emb['repo_id']} (pin: "
                            f"{pins.get('model:' + emb['repo_id'], {}).get('commit', 'n/a')})"],
        ["Vector store", "FAISS flat, inner product on L2-normalised vectors (= cosine)"],
        ["Top-k", cfg.get_path("retrieval.top_k")],
        ["Generation model", f"{gen['repo_id']} (pin: "
                             f"{pins.get('model:' + gen['repo_id'], {}).get('commit', 'n/a')})"],
        ["Re-ranking", "none (System A non-goal)"],
        ["Graph logic", "none (System A non-goal)"]]))
    L.append("\n**Model deviation from arXiv:2601.08773 (stated, not hidden):** the paper "
             "uses Gemini for embedding and generation; this replication uses "
             f"`{emb['repo_id']}` and `{gen['repo_id']}` (open-weight). Leg 1 therefore "
             "validates the *relative* A/B/C pattern, not absolute numeric parity.\n")

    L.append("### Corpus / chunk counts vs. the paper\n")
    rows = []
    for m in indexes:
        pc = m.get("paper_chunks")
        delta = f"{(m['chunks'] - pc) / pc * 100:+.1f}%" if pc else None
        rows.append([m["repo"], (m.get("commit") or "unpinned")[:10], m["files"],
                     m.get("paper_files"), m["chunks"], pc, delta])
    L.append(_table(["Repo", "Commit", "Files (ours)", "Files (paper)",
                     "Chunks (ours)", "Chunks (paper)", "Chunk delta"], rows)
             if rows else "_MISSING: no indexes built yet._")
    L.append("\nDeltas are expected when the repo snapshot differs from the paper's; "
             "explain each one in section 6.\n")

    # 2. Leg 1
    L.append("## 2. Leg 1 results - QA replication\n")
    leg1 = _load(_latest(res / "leg1"), "leg1_results.json") if (res / "leg1").exists() else None
    if leg1:
        rows = [[repo, s.get("n_questions"), s.get("keyword_coverage"),
                 s.get("edit_similarity_to_reference"),
                 (s.get("retrieval_latency") or {}).get("p50"),
                 (s.get("generation_latency") or {}).get("p50")]
                for repo, s in leg1["summary"].items()]
        L.append(_table(["Repo", "N", "Rubric coverage", "ES vs reference",
                         "Retrieval p50 (s)", "Generation p50 (s)"], rows))
        L.append("\n_Before submitting, add two columns: 2601.08773's own System-A accuracy "
                 "per repo, and your human / LLM-judge accuracy._\n")
    else:
        L.append("_MISSING: run `python -m systems.system_a.run_leg1`._\n")

    # 3. Leg 2
    L.append("## 3. Leg 2 results - generation\n")
    rows = []
    for leg_dir in sorted(res.glob("leg2-*")):
        data = _load(_latest(leg_dir), "leg2_*_results.json")
        if not data:
            continue
        s = data["summary"]
        rows.append([leg_dir.name.replace("leg2-", ""), s.get("n_tasks") or s.get("n_queries"),
                     s.get("pass@1"), s.get("pass@3"), s.get("pass@5"),
                     s.get("exact_match"), s.get("edit_similarity")])
    L.append(_table(["Dataset", "N", "pass@1", "pass@3", "pass@5", "EM", "ES"], rows)
             if rows else "_MISSING: run `python -m systems.system_a.run_leg2 --dataset ...`._")
    L.append("")

    # 4. Cost
    L.append("## 4. Cost table\n")
    rows = [[m["repo"], m["chunks"], m["indexing_wall_clock_s"],
             f"{m['indexing_embed_tokens']:,}", "$0.00 (open-weight, local)",
             m["index_size_mb"]] for m in indexes]
    L.append(_table(["Repo", "Chunks", "Indexing wall-clock (s)", "Indexing embed tokens",
                     "Indexing $ cost", "Index size (MB)"], rows)
             if rows else "_MISSING: no indexes built yet._")

    rows = []
    for leg_dir in sorted(list(res.glob("leg1")) + list(res.glob("leg2-*"))):
        data = _load(_latest(leg_dir), "*_results.json")
        if not data:
            continue
        s = data["summary"]
        if isinstance(s, dict) and "overall" in s:
            merged = {}
            for v in s.values():
                if isinstance(v, dict):
                    merged.update({k: vv for k, vv in v.items() if k not in merged})
            s = merged
        rl, gl = s.get("retrieval_latency") or {}, s.get("generation_latency") or {}
        rows.append([leg_dir.name, rl.get("p50"), rl.get("p95"), gl.get("p50"), gl.get("p95"),
                     s.get("total_prompt_tokens"), s.get("total_completion_tokens")])
    if rows:
        L.append("\n" + _table(["Run", "Retrieval p50", "Retrieval p95", "Generation p50",
                                "Generation p95", "Prompt tokens", "Completion tokens"], rows))
    L.append("")

    # 5. Retrieval quality
    L.append("## 5. Retrieval quality (held-out queries)\n")
    k = cfg.get_path("retrieval.top_k")
    rows = []
    for leg_dir in sorted(res.glob("leg2-*")):
        data = _load(_latest(leg_dir), "leg2_*_results.json")
        if not data or "retrieval" not in data.get("summary", {}):
            continue
        r = data["summary"]["retrieval"]
        rows.append([leg_dir.name.replace("leg2-", ""), data["summary"].get("n_queries"),
                     r.get("precision"), r.get("recall"), r.get("f1")])
    L.append(_table(["Dataset", "N", f"Precision@{k}", f"Recall@{k}", "F1"], rows)
             if rows else "_MISSING: run the held-out leg (`--dataset frappe`)._")
    L.append("")

    # 6. Known deviations
    L.append("## 6. Known deviations from arXiv:2601.08773\n")
    L.append("- **Models**: Qwen3-Embedding + Qwen2.5-Coder instead of Gemini (open-weight, "
             "free). Relative pattern replicated; absolute numbers not directly comparable.\n"
             "- **Repo snapshot**: repos pinned to the commits in section 1; the paper's "
             "snapshot is earlier, so file/chunk counts differ (see delta column).\n"
             "- **QA question set**: the paper's exact 45 questions are unpublished; the set in "
             "`systems/system_a/eval/leg1_questions.json` is a reconstructed comparable set "
             "(same 15-per-repo structure, same target categories).\n"
             "- **Leg 1 scoring**: state whether you used the automatic rubric, an LLM judge, "
             "or human grading.\n"
             "- **CoderEval harness**: state whether you used the official Docker harness or "
             "the local subprocess runner in `shared/exec_eval.py`.\n"
             "- _Add anything else you changed, and why._\n")

    out = res / "report_system_a.md"
    out.write_text("\n".join(L), encoding="utf-8")
    return out


if __name__ == "__main__":
    argparse.ArgumentParser(description="Build the System A report").parse_args()
    print(f"[report] wrote {build_report()}")
